version: '2.3'
services:
  lidar_jay_ros:
    image: lidar_jay_ros
    container_name: lidar_jay_ros
    build:
      # docker build context
      context: .
      dockerfile: ./Dockerfile.dockerfile
      args:
        - ROS_DISTRO=melodic
        - ROS_HOSTNAME= $HOSTNAME
        - HOSTNAME= $HOSTNAME
        - user_id=1000
        - group_id=1000
    privileged: true
    security_opt:
      - seccomp:unconfined
    volumes:
      # mmpug workspace
      - ./../ws/:/home/developer/lidar_jay_ws
      # gui configurations
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /dev/input:/dev/input
      - /dev/:/dev/
      - /etc/hosts:/etc/hosts
      - /var/log/syslog:/syslog

    environment:
      - ROS_SOURCED_WORKSPACE=/home/developer/lidar_jay_ws/ros_ws/devel/setup.bash
      # Set environment params for GUI container passthrough
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      # - QT_QPA_PLATFORM='offscreen'
      # deployer export for exec call
      # Set the hostnames of different systems
      - HOSTNAME=${HOSTNAME}
      - ROS_MASTER_IP=${HOSTNAME}
      - ROS_HOSTNAME=${HOSTNAME}
    entrypoint:
      - /docker-entrypoint/ws-shell.bash
    tty: true
    # use host network
    network_mode: "host"
